name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Run unit tests
        run: |
          bats tests/unit/

      - name: Run integration tests
        run: |
          bats tests/integration/

      - name: Run all tests
        run: |
          bats tests/
